//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        
        public int Id { get; set; }
        public string CateName { get; set; }
        public int ParentId { get; set; }
    
        public virtual Category Categories1 { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
